In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import NMF

In [2]:
transactions = pd.read_csv("transactions_train.csv")

In [3]:
customers = pd.read_csv("customers.csv")
articles = pd.read_csv("articles.csv")
customers.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...

In [4]:
# top_customers_id = customers[0:10000]
# top_articles_id = articles[0:10000]

In [5]:
# no_of_rows = top_customers_id.shape[0]
# no_of_columns = top_articles_id.shape[0]
# user_item_matrix = np.zeros((no_of_rows, no_of_columns))
# df = pd.DataFrame(user_item_matrix, columns = top_customers_id['customer_id'], index = top_articles_id['article_id'])
# df

In [6]:
# specific_transactions_customer = transactions[transactions['customer_id'].isin(top_customers_id['customer_id'])]
# specific_transactions_overall = specific_transactions_customer[specific_transactions_customer['article_id'].isin(top_articles_id['article_id'])]

# for index, each_transaction in specific_transactions_overall.iterrows():
#     c_id = each_transaction['customer_id']
#     a_id = each_transaction['article_id']
#     df.loc[a_id, c_id] = 1

In [7]:
# df

In [6]:
transactions['Bought'] = 1
transactions

/Users/tejasbhuwania/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,t_dat,customer_id,article_id,price,sales_channel_id,Bought
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2,1
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2,1
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2,1
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2,1
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2,1
...,...,...,...,...,...,...
995,2018-09-20,05943a58bd172641b80919a9bdf14012df940800bc74d0...,661794001,0.152525,2,1
996,2018-09-20,05943a58bd172641b80919a9bdf14012df940800bc74d0...,661794001,0.152525,2,1
997,2018-09-20,05943a58bd172641b80919a9bdf14012df940800bc74d0...,661794002,0.152525,2,1
998,2018-09-20,05943a58bd172641b80919a9bdf14012df940800bc74d0...,661794002,0.152525,2,1
999,2018-09-20,059d4230aeb70d519fb5e5e5ec8f5efc6c3eaad65b06af...,516903005,0.033881,2,1

In [18]:
transactions = transactions[0:1000]
df = transactions.pivot_table(index = 'customer_id', columns ='article_id', values = 'Bought').fillna(0)
df

article_id,156231001,156231002,176550020,179208001,186262006,186264014,188183009,211143022,211143037,212042043,...,700819006,701398001,702072001,703193001,704048006,710390001,714373001,714417001,720384002,728162002
customer_id,,,,,,,,,,,,,,,,,,,,,
000058a12d5b43e67d225668fa1f8d618c13dc232df0cad8ffe7ad4a1091e318,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00007d2de826758b65a93dd24ce629ed66842531df6699338c5570910a014cc2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00083cda041544b2fbb0e0d2905ad17da7cf1007526fb4c73235dccbbc132280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0008968c0d451dbc5a9968da03196fe20051965edde7413775c4eb3be9abe9c2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000aa7f0dc06cd7174389e76c9e132a67860c5f65f970699daccc14425ac31a8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
057e275b214b3d97a8caa75a3b802bf2ffda4d490189a1b4271a7a38658556e3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05887aca6a1742c97497dded62e474cc10b5c5d783eaffa4663e364e72a99d6e,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0592e247fc4388fe73eaacb8d8577e5d817b4b0c7e679cb9b5693d34744cdc88,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
05943a58bd172641b80919a9bdf14012df940800bc74d0707abdd38efc1dd4f1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
059d4230aeb70d519fb5e5e5ec8f5efc6c3eaad65b06af8810c7fb6be64e20ab,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
all_ids = df.index.values.tolist()

R = df.to_numpy()
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)


from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 10)

sigma = np.diag(sigma)

all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = df.columns)

In [22]:
R = df.to_numpy()
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)

In [23]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 10)

In [24]:
sigma = np.diag(sigma)

In [25]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = df.columns)

In [26]:
all_user_predicted_ratings

array([[ 0.00264622,  0.00264622,  0.00291029, ...,  0.00264622,
         0.00263077,  0.00264622],
       [ 0.00157254,  0.00157254, -0.00361066, ...,  0.00157254,
         0.00194149,  0.00157254],
       [ 0.0071501 ,  0.0071501 ,  0.00882585, ...,  0.0071501 ,
         0.0070617 ,  0.0071501 ],
       ...,
       [ 0.00925376,  0.00925376, -0.00417042, ...,  0.00925376,
         0.0096754 ,  0.00925376],
       [ 0.00395835,  0.00395835,  0.00451908, ...,  0.00395835,
         0.00393261,  0.00395835],
       [ 0.00131539,  0.00131539,  0.00143518, ...,  0.00131539,
         0.00130832,  0.00131539]])

In [27]:
preds_df

article_id,156231001,156231002,176550020,179208001,186262006,186264014,188183009,211143022,211143037,212042043,...,700819006,701398001,702072001,703193001,704048006,710390001,714373001,714417001,720384002,728162002
0,0.002646,0.002646,0.002910,0.002758,0.002665,0.002665,0.002927,0.002665,0.002646,0.002724,...,0.000782,0.002646,0.002862,0.002681,0.002665,0.002665,0.002646,0.002646,0.002631,0.002646
1,0.001573,0.001573,-0.003611,-0.000913,0.001132,0.001132,-0.005668,0.001132,0.001573,-0.000189,...,-0.016679,0.001573,-0.002721,0.000758,0.001132,0.001132,0.001573,0.001573,0.001941,0.001573
2,0.007150,0.007150,0.008826,0.007823,0.007259,0.007259,0.009628,0.007259,0.007150,0.007617,...,-0.000463,0.007150,0.008511,0.007349,0.007259,0.007259,0.007150,0.007150,0.007062,0.007150
3,0.002646,0.002646,0.002910,0.002758,0.002665,0.002665,0.002927,0.002665,0.002646,0.002724,...,0.000782,0.002646,0.002862,0.002681,0.002665,0.002665,0.002646,0.002646,0.002631,0.002646
4,0.004354,0.004354,-0.006983,-0.001628,0.003216,0.003216,-0.009509,0.003216,0.004354,0.000049,...,0.980209,0.004354,-0.005104,0.002224,0.003216,0.003216,0.004354,0.004354,0.005335,0.004354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,0.001315,0.001315,0.001435,0.001366,0.001324,0.001324,0.001438,0.001324,0.001315,0.001351,...,0.000448,0.001315,0.001413,0.001331,0.001324,0.001324,0.001315,0.001315,0.001308,0.001315
298,0.001315,0.001315,0.001435,0.001366,0.001324,0.001324,0.001438,0.001324,0.001315,0.001351,...,0.000448,0.001315,0.001413,0.001331,0.001324,0.001324,0.001315,0.001315,0.001308,0.001315
299,0.009254,0.009254,-0.004170,0.005053,0.008694,0.008694,-0.027547,0.008694,0.009254,0.006459,...,-0.003992,0.009254,-0.001395,0.008258,0.008694,0.008694,0.009254,0.009254,0.009675,0.009254
300,0.003958,0.003958,0.004519,0.004168,0.003991,0.003991,0.004775,0.003991,0.003958,0.004102,...,0.000397,0.003958,0.004411,0.004017,0.003991,0.003991,0.003958,0.003958,0.003933,0.003958
301,0.001315,0.001315,0.001435,0.001366,0.001324,0.001324,0.001438,0.001324,0.001315,0.001351,...,0.000448,0.001315,0.001413,0.001331,0.001324,0.001324,0.001315,0.001315,0.001308,0.001315

In [28]:
def recommend_movies(predictions_df, userID, movies_df, original_ratings_df, num_recommendations=5):
    
    # Get and sort the user's predictions
    user_row_number = userID - 1 # UserID starts at 1, not 0
    sorted_user_predictions = predictions_df.iloc[user_row_number].sort_values(ascending=False)
    
    # Get the user's data and merge in the movie information.
    user_data = original_ratings_df[original_ratings_df.customer_id == (userID)]
    user_full = (user_data.merge(movies_df, how = 'left', left_on = 'article_id', right_on = 'article_id').
                     sort_values(['Bought'], ascending=False)
                 )

#     print 'User {0} has already rated {1} movies.'.format(userID, user_full.shape[0])
#     print 'Recommending the highest {0} predicted ratings movies not already rated.'.format(num_recommendations)
    
    # Recommend the highest predicted rating movies that the user hasn't seen yet.
    recommendations = (movies_df[~movies_df['article_id'].isin(user_full['article_id'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'article_id',
               right_on = 'article_id').
         rename(columns = {user_row_number: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )

    return user_full, recommendations

already_rated, predictions = recommend_movies(preds_df, 300, articles, transactions, 10)

In [30]:
predictions

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
39397,661308001,661308,Cambera,265,Dress,Garment Full body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Long dress in slub jersey made from a modal an...
10317,539878003,539878,Skirt Mini,275,Skirt,Garment Lower body,1010023,Denim,71,Light Blue,...,Denim Other Garments,D,Divided,2,Divided,57,Ladies Denim,1016,Trousers Denim,Short 5-pocket skirt in washed denim with hard...
28581,623474001,623474,DT AG Saphire,275,Skirt,Garment Lower body,1010016,Solid,19,Greenish Khaki,...,Skirt,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1012,Skirts,ANNA GLOVER x H&M. Short skirt in sturdy cotto...
866,299733008,299733,Hilton,265,Dress,Garment Full body,1010016,Solid,1,Other,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Strapless jersey dress with an elasticated wai...
35523,647190001,647190,Strada,275,Skirt,Garment Lower body,1010017,Stripe,10,White,...,Skirt,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1012,Skirts,Short skirt in jersey with an elasticated wais...
32785,636421003,636421,Merci,275,Skirt,Garment Lower body,1010001,All over pattern,10,White,...,Skirt,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1012,Skirts,Short skirt in a patterned crêpe weave with a ...
30161,627101006,627101,Evelyn Rib dress,265,Dress,Garment Full body,1010017,Stripe,9,Black,...,Basic 1,D,Divided,2,Divided,51,Divided Basics,1002,Jersey Basic,Short dress in ribbed cotton jersey with short...
36230,649683001,649683,Julietta,275,Skirt,Garment Lower body,1010017,Stripe,93,Dark Green,...,Skirt,A,Ladieswear,1,Ladieswear,15,Womens Everyday Collection,1012,Skirts,"Asymmetric skirt in a patterned, textured weav..."
19333,583558001,583558,Noel denim dress,265,Dress,Garment Full body,1010023,Denim,72,Blue,...,Dresses,D,Divided,2,Divided,53,Divided Collection,1013,Dresses Ladies,"Short, fitted dress in stretch denim with a co..."
24686,610234003,610234,dean dress,265,Dress,Garment Full body,1010001,All over pattern,81,Light Turquoise,...,Projects Dresses,D,Divided,2,Divided,50,Divided Projects,1013,Dresses Ladies,"Sleeveless dress in a crinkled, patterned weav..."